# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - demointec

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - demointec

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 1. Build Frontend
      - name: Build Frontend
        working-directory: ./Frontend-INTEC
        run: |
          npm install
          npm run build

      # 2. Build Backend
      - name: Build Backend
        working-directory: ./Back-INTEC
        run: |
          npm install
          npm run build

      # 3. Prepare Artifact
      # Create 'public' folder in Back-INTEC and copy frontend build there
      - name: Copy Frontend to Backend Public
        run: |
          mkdir -p Back-INTEC/public
          cp -r Frontend-INTEC/dist/frontend-app/browser/* Back-INTEC/public/

      # 4. Upload Backend (with included frontend in public) as artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./Back-INTEC

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C51C80EB2AE449D97982B6754A65CC6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B5E618DB6654048A1DB3BD563BA0E47 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_90268B49B140499F9C8BB2B87487E5FE }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'demointec'
          slot-name: 'Production'
          package: .